import type { Metadata } from "next";
import { Inter, Dosis } from "next/font/google";
import { Providers } from "./providers"
import "./globals.css";
import { loadErrorMessages, loadDevMessages } from "@apollo/client/dev";

const inter = Dosis({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  if (true) {
    // Adds messages only in a dev environment
    loadDevMessages();
    loadErrorMessages();
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="max-w-screen-2xl mx-auto relative">
          <Providers>
            {children}
          </Providers>
        </div>
      </body>
    </html>
  );
}
